<?xml version="1.0" encoding="utf-8"?><Database Name="Student Information" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-GT966OV\SQLEXPRESS01;Initial Catalog=&quot;Student Information&quot;;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="Student_Information_System.Properties.Settings" SettingsPropertyName="Student_InformationConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccountDetails" Member="AccountDetails">
    <Type Name="AccountDetail">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.EmergencyContact" Member="EmergencyContacts">
    <Type Name="EmergencyContact">
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GuardianName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GuardianAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Relationship" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmergencyContactNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentDetail_EmergencyContact" Member="StudentDetails" ThisKey="StudentID" OtherKey="StudentID" Type="StudentDetails" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParentDetails" Member="ParentDetails">
    <Type Name="ParentDetails">
      <Column Name="ParentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MotherName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MotherOccupation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MotherContactNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FatherOccupation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FatherContactNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentDetail_ParentDetail" Member="StudentDetails" ThisKey="StudentID" OtherKey="StudentID" Type="StudentDetails" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SiblingDetails" Member="SiblingDetails">
    <Type Name="SiblingDetails">
      <Column Name="SiblingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentDetail_SiblingDetail" Member="StudentDetails" ThisKey="StudentID" OtherKey="StudentID" Type="StudentDetails" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentDetails" Member="StudentDetails">
    <Type Name="StudentDetails">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HomeAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="StudentDetail_EmergencyContact" Member="EmergencyContacts" ThisKey="StudentID" OtherKey="StudentID" Type="EmergencyContact" />
      <Association Name="StudentDetail_ParentDetail" Member="ParentDetails" ThisKey="StudentID" OtherKey="StudentID" Type="ParentDetails" />
      <Association Name="StudentDetail_SiblingDetail" Member="SiblingDetails" ThisKey="StudentID" OtherKey="StudentID" Type="SiblingDetails" />
    </Type>
  </Table>
</Database>